/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.sql.ResultSet;
import static javax.management.Query.value;
/**
 *
 * @author windows-10
 */
public class BudgetSummary extends javax.swing.JPanel {

    /**
     * Creates new form BudgetSummary
     */
    public BudgetSummary() {
        initComponents();
        Connect();
    }

    Connection con; 
    ResultSet rs;
    Statement statement;
    public void Connect() {
        String url = "jdbc:mysql://localhost/cashcontrol_db";
        String username = "root";
        String password = "";

        int expense = 0;
        int budget = 0;

        try (Connection connection = DriverManager.getConnection(url, username, password)) {
            // Retrieve average budget amount
            String budgetQuery = "SELECT AVG(budgetAmount) AS average FROM budgettable";
            try (Statement statement = connection.createStatement();
                 ResultSet rs = statement.executeQuery(budgetQuery)) {
                if (rs.next()) {
                    double budgetAverage = rs.getDouble("average");
                    System.out.println("Average Budget: " + budgetAverage);
                    String aveSTR = String.valueOf(budgetAverage);
                    totalBlbl.setText(aveSTR);
                    budget = (int) budgetAverage; // Assign the average budget value to 'budget' variable
                }
            }

            // Retrieve average expense amount
            String expenseQuery = "SELECT AVG(ExpenseAmount) AS average FROM expensestable";
            try (Statement statement2 = connection.createStatement();
                 ResultSet rs2 = statement2.executeQuery(expenseQuery)) {
                if (rs2.next()) {
                    int expenseAverage = rs2.getInt("average");
                    System.out.println("Average Expense: " + expenseAverage);
                    String expenseStr = String.valueOf(expenseAverage);
                    totalElbl.setText(expenseStr);
                    expense = expenseAverage; // Assign the average expense value to 'expense' variable
                }
            }

            int balance = budget - expense;
            String balanceStr = String.valueOf(balance);
            remBlbl.setText(balanceStr);

            Color DGREEN = new Color(138,156,107);
            budgetTtl.setForeground(DGREEN);
            remB.setForeground(DGREEN);
            remB.setMaximum(budget);
            totalE.setForeground(DGREEN);
            remB.setMinimum(0);
            totalE.setMaximum(budget);
            totalE.setMinimum(0);

            int budgetPer = (int) ((balance /budget) * 100);
            int expensePercentage = (int) ((expense / budget) * 100);
            totalE.setValue(expensePercentage);
            remB.setValue(budgetPer);
            System.out.println("Expense: " + expense);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddBtn = new javax.swing.JLabel();
        remB = new javax.swing.JProgressBar();
        totalE = new javax.swing.JProgressBar();
        remBlbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalElbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        budgetTtl = new javax.swing.JProgressBar();
        totalBlbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(740, 325));

        AddBtn.setBackground(new java.awt.Color(248, 247, 242));
        AddBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-add-new-50.png"))); // NOI18N

        remB.setBackground(new java.awt.Color(252, 252, 252));
        remB.setForeground(new java.awt.Color(0, 0, 0));
        remB.setBorder(null);
        remB.setBorderPainted(false);

        totalE.setBackground(new java.awt.Color(252, 252, 252));
        totalE.setForeground(new java.awt.Color(0, 0, 0));
        totalE.setBorder(null);
        totalE.setBorderPainted(false);

        remBlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        remBlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        remBlbl.setText("150");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("REMAINING BUDGET");

        totalElbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalElbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalElbl.setText("350");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("TOTAL EXPENSES");

        budgetTtl.setBackground(new java.awt.Color(252, 252, 252));
        budgetTtl.setForeground(new java.awt.Color(0, 0, 0));
        budgetTtl.setToolTipText("");
        budgetTtl.setBorder(null);
        budgetTtl.setBorderPainted(false);
        budgetTtl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        totalBlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalBlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalBlbl.setText("500");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("TOTAL BUDGET");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/summaryBudget.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalBlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(budgetTtl, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalElbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(totalE, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(remBlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(remB, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(AddBtn)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(totalBlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(budgetTtl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(remBlbl))
                        .addGap(18, 18, 18)
                        .addComponent(remB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(totalElbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddBtn)
                            .addComponent(totalE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddBtn;
    private javax.swing.JProgressBar budgetTtl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar remB;
    private javax.swing.JLabel remBlbl;
    private javax.swing.JLabel totalBlbl;
    private javax.swing.JProgressBar totalE;
    private javax.swing.JLabel totalElbl;
    // End of variables declaration//GEN-END:variables
}
