/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms;

import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author windows-10
 */
public class BudgetMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExpenseMenuPanel
     */
    public BudgetMenuPanel() {
        initComponents();
        Connect();
            
        
      
    
    }
    
    
    Connection con; 
    java.sql.ResultSet rs;
    Statement statement;
    public void Connect() {
        
        String url = "jdbc:mysql://localhost/cashcontrol_db";
        String username = "root";
        String password = "";

        int expense = 0;
        int budget = 0;
        try (Connection connection = DriverManager.getConnection(url, username, password)) {
            String BudgetQ = "SELECT SUM(budgetAmount) AS sum FROM budgettable";
            try (Statement statement = connection.createStatement();
                 java.sql.ResultSet rs = statement.executeQuery(BudgetQ)) {
                if (rs.next()) {
                    double BudgetAve = rs.getDouble("sum");
                    System.out.println("BudgetSum: " + BudgetAve);
                    String aveSTR = String.valueOf(BudgetAve);
                    totalBlbl.setText(aveSTR); 
                    budget = (int) BudgetAve;
                    
                    
                }
            }

            String ExpQ = "SELECT SUM(expenseAmount) AS sum FROM expensetable";
            try (Statement statement2 = connection.createStatement();
                 java.sql.ResultSet rs2 = statement2.executeQuery(ExpQ)) {
                if (rs2.next()) {
                    int ExpAve = rs2.getInt("sum"); // Changed from rs.getInt("average") to rs2.getInt("average")
                    System.out.println("Expense Sum: " + ExpAve);
                    
                    expense = ExpAve;
                }
            }
            
            String ExpStr = String.valueOf(expense);
            totalElbl.setText(ExpStr);
                    
            int bal = budget - expense;
            String balance = String.valueOf(bal);
            remBlbl.setText(balance);
           
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        
            remB.setMaximum(budget);
            remB.setMinimum(0);
            totalE.setMaximum(budget); 
            totalE.setMinimum(0);
           
                int valueBal = (int) (budget/expense)*100;
                
                remB.setValue(valueBal);
                totalE.setValue(expense);
                
            //int value = (int) ((percentage / 100.0) * (maxValue - minValue) + minValue);        
            revalidate();
            repaint();
    }
    PreparedStatement pst; 
    ResultSetMetaData rss;
    DefaultTableModel df; 
    
    private void switchToMenuPanelBudget(){
        BudgetMenuPanel bmp = new BudgetMenuPanel(); 
        Home home = (Home) SwingUtilities.getWindowAncestor(this);

        // Remove the current panel (AddExpensePanel)
        home.getMenuBoard().remove(this);

        // Add the ExpenseMenuPanel
        bmp.setSize(900, 450);
        home.getMenuBoard().add(bmp);
        home.getMenuBoard().revalidate();
        home.getMenuBoard().repaint();
    }
    private void switchToMenuPanelRecords(){
        BudgetRecords br = new BudgetRecords(); 
        br.setSize(740, 325);
        ExpenseAddPanel.removeAll();
        ExpenseAddPanel.add(br).setVisible(true);
        ExpenseAddPanel.revalidate();
        ExpenseAddPanel.repaint();
        // Add the ExpenseMenuPanel
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddBtnPanel = new javax.swing.JPanel();
        BudAddBtn = new javax.swing.JLabel();
        ExpenseAddPanel = new javax.swing.JPanel();
        budsum = new javax.swing.JPanel();
        remB = new javax.swing.JProgressBar();
        totalE = new javax.swing.JProgressBar();
        remBlbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalElbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        totalBlbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bTblPanel = new javax.swing.JPanel();
        BudTblBtn = new javax.swing.JLabel();
        BudRecPanel = new javax.swing.JPanel();
        BudRecBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 247, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddBtnPanel.setBackground(new java.awt.Color(248, 247, 242));
        AddBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnPanelMouseClicked(evt);
            }
        });

        BudAddBtn.setBackground(new java.awt.Color(107, 112, 92));
        BudAddBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BudAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/addDark.png"))); // NOI18N
        BudAddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BudAddBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AddBtnPanelLayout = new javax.swing.GroupLayout(AddBtnPanel);
        AddBtnPanel.setLayout(AddBtnPanelLayout);
        AddBtnPanelLayout.setHorizontalGroup(
            AddBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBtnPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BudAddBtn)
                .addContainerGap())
        );
        AddBtnPanelLayout.setVerticalGroup(
            AddBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBtnPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BudAddBtn)
                .addContainerGap())
        );

        add(AddBtnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 60, 60));

        ExpenseAddPanel.setBackground(new java.awt.Color(248, 247, 242));

        budsum.setBackground(new java.awt.Color(248, 247, 242));
        budsum.setPreferredSize(new java.awt.Dimension(740, 325));

        remB.setBackground(new java.awt.Color(252, 252, 252));
        remB.setForeground(new java.awt.Color(138, 156, 107));
        remB.setValue(5);

        totalE.setBackground(new java.awt.Color(252, 252, 252));
        totalE.setForeground(new java.awt.Color(138, 156, 107));
        totalE.setValue(25);

        remBlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        remBlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        remBlbl.setText("150");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("REMAINING BUDGET");

        totalElbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalElbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalElbl.setText("350");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("TOTAL EXPENSES");

        jProgressBar3.setBackground(new java.awt.Color(252, 252, 252));
        jProgressBar3.setForeground(new java.awt.Color(138, 156, 107));
        jProgressBar3.setToolTipText("");
        jProgressBar3.setValue(100);

        totalBlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalBlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalBlbl.setText("500");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("TOTAL BUDGET");

        jPanel3.setBackground(new java.awt.Color(248, 247, 242));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/summaryBudget.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout budsumLayout = new javax.swing.GroupLayout(budsum);
        budsum.setLayout(budsumLayout);
        budsumLayout.setHorizontalGroup(
            budsumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, budsumLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(budsumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(budsumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, budsumLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalElbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(totalE, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(budsumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, budsumLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(remBlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(remB, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(budsumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, budsumLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalBlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115))
        );
        budsumLayout.setVerticalGroup(
            budsumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(budsumLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(budsumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, budsumLayout.createSequentialGroup()
                        .addGroup(budsumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(totalBlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(budsumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(remBlbl))
                        .addGap(18, 18, 18)
                        .addComponent(remB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(budsumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(totalElbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, budsumLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );

        javax.swing.GroupLayout ExpenseAddPanelLayout = new javax.swing.GroupLayout(ExpenseAddPanel);
        ExpenseAddPanel.setLayout(ExpenseAddPanelLayout);
        ExpenseAddPanelLayout.setHorizontalGroup(
            ExpenseAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(ExpenseAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExpenseAddPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(budsum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ExpenseAddPanelLayout.setVerticalGroup(
            ExpenseAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(ExpenseAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExpenseAddPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(budsum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(ExpenseAddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 740, 350));

        bTblPanel.setBackground(new java.awt.Color(248, 247, 242));
        bTblPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTblPanelMouseClicked(evt);
            }
        });

        BudTblBtn.setBackground(new java.awt.Color(248, 247, 242));
        BudTblBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BudTblBtn.setForeground(new java.awt.Color(107, 112, 92));
        BudTblBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BudTblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bTblLight.png"))); // NOI18N
        BudTblBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BudTblBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bTblPanelLayout = new javax.swing.GroupLayout(bTblPanel);
        bTblPanel.setLayout(bTblPanelLayout);
        bTblPanelLayout.setHorizontalGroup(
            bTblPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bTblPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BudTblBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bTblPanelLayout.setVerticalGroup(
            bTblPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bTblPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BudTblBtn)
                .addContainerGap())
        );

        add(bTblPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 60, 60));

        BudRecPanel.setBackground(new java.awt.Color(248, 248, 242));

        BudRecBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BudRecBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rec.png"))); // NOI18N
        BudRecBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BudRecBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BudRecPanelLayout = new javax.swing.GroupLayout(BudRecPanel);
        BudRecPanel.setLayout(BudRecPanelLayout);
        BudRecPanelLayout.setHorizontalGroup(
            BudRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BudRecPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BudRecBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BudRecPanelLayout.setVerticalGroup(
            BudRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BudRecPanelLayout.createSequentialGroup()
                .addComponent(BudRecBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(BudRecPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 60, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void BudAddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BudAddBtnMouseClicked
        // TODO add your handling code here:
      
        
        AddBudgetPanel abp = new AddBudgetPanel();
        abp.setSize(740, 350);
        ExpenseAddPanel.removeAll();
        ExpenseAddPanel.add(abp).setVisible(true); 
        ExpenseAddPanel.revalidate();
        ExpenseAddPanel.repaint();
        System.out.println("Panel visibility: " + abp.isVisible());
        System.out.println("Panel size: " + abp.getSize());
        System.out.println("Panel location: " + abp.getLocation());
        
        
        
        
        
    }//GEN-LAST:event_BudAddBtnMouseClicked

    private void AddBtnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnPanelMouseClicked
       
        AddBudgetPanel abp = new AddBudgetPanel();
        abp.setSize(740, 350);
        ExpenseAddPanel.removeAll();
        ExpenseAddPanel.add(abp).setVisible(true); 

        System.out.println("Panel visibility: " + abp.isVisible());
        System.out.println("Panel size: " + abp.getSize());
        System.out.println("Panel location: " + abp.getLocation());

        
        
    }//GEN-LAST:event_AddBtnPanelMouseClicked

    private void BudTblBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BudTblBtnMouseClicked
        // TODO add your handling code here:
       
        switchToMenuPanelBudget();
    }//GEN-LAST:event_BudTblBtnMouseClicked

    private void bTblPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTblPanelMouseClicked
        // TODO add your handling code here:
           
        
        switchToMenuPanelBudget();
    }//GEN-LAST:event_bTblPanelMouseClicked

    private void BudRecBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BudRecBtnMouseClicked
        // TODO add your handling code here:
        switchToMenuPanelRecords();
    }//GEN-LAST:event_BudRecBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddBtnPanel;
    private javax.swing.JLabel BudAddBtn;
    private javax.swing.JLabel BudRecBtn;
    private javax.swing.JPanel BudRecPanel;
    private javax.swing.JLabel BudTblBtn;
    private javax.swing.JPanel ExpenseAddPanel;
    private javax.swing.JPanel bTblPanel;
    private javax.swing.JPanel budsum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar remB;
    private javax.swing.JLabel remBlbl;
    private javax.swing.JLabel totalBlbl;
    private javax.swing.JProgressBar totalE;
    private javax.swing.JLabel totalElbl;
    // End of variables declaration//GEN-END:variables
}
