/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms;

import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.*; 
import java.sql.ResultSet; 

/**
 *
 * @author windows-10
 */
public class BudgetRecords extends javax.swing.JPanel {

    /**
     * Creates new form BudgetRecords
     */
    public BudgetRecords() {
        initComponents();
        Connect();
    }
    Connection con; 
    ResultSet rs; 
    ResultSetMetaData rss;
    DefaultTableModel df; 
    PreparedStatement pst; 
        public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cashcontrol_db", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddExpensePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddExpensePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        Fetch();
       
   } 
    private void Fetch(){
        try {
            int q;
            pst = con.prepareStatement("SELECT * FROM budgettable");
            rs = pst.executeQuery();
            
            rss = rs.getMetaData();
            q = rss.getColumnCount();
            
            df =(DefaultTableModel)recTable.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for (int i = 1 ; i <= q ; i++){
                    v2.add(rs.getString("budget_id"));
                    v2.add(rs.getString("date"));
                    v2.add(rs.getString("category"));
                    v2.add(rs.getString("budgetAmount"));
                   
                }
                df.addRow(v2);
            } 
                    } catch (SQLException ex) {
            Logger.getLogger(ExpenseMenuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        recTable = new javax.swing.JTable();
        DeleteBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 247, 242));

        recTable.setBackground(new java.awt.Color(248, 247, 242));
        recTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recTable.setForeground(new java.awt.Color(107, 112, 92));
        recTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "BUDGET_ID", "DATE", "CATEGORY", "AMOUNT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        recTable.setGridColor(new java.awt.Color(107, 112, 92));
        recTable.setIntercellSpacing(new java.awt.Dimension(1, 1));
        recTable.setRowHeight(30);
        recTable.setSelectionBackground(new java.awt.Color(183, 183, 164));
        recTable.setSelectionForeground(new java.awt.Color(248, 247, 242));
        jScrollPane1.setViewportView(recTable);

        DeleteBtn.setBackground(new java.awt.Color(107, 112, 92));
        DeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("DELETE");
        DeleteBtn.setBorder(null);
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 112, 92));
        jLabel1.setText("YOUR BUDGET RECORDS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        int[] x = recTable.getSelectedRows();

        for (int i = 0 ; i < x.length ; i++){
            try {
                Object xz = df.getValueAt(x[i],0);
                pst = con.prepareStatement("DELETE FROM budgettable WHERE budget_id = ?");
                System.out.println(xz.toString());

                pst.setString(1, xz.toString());
                pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ExpenseMenuPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Fetch();
    }//GEN-LAST:event_DeleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable recTable;
    // End of variables declaration//GEN-END:variables
}
