/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author windows-10
 */
public class ContactMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContactMenuPanel
     */
    public ContactMenuPanel() {
        initComponents();
        Connect();
    }
    
    Connection con; 
    PreparedStatement pst;
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cashcontrol_db", "root", "");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MsgTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MsgSub = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(107, 112, 92));
        jLabel1.setText("Email");

        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(107, 112, 92)));

        MsgTxt.setBackground(new java.awt.Color(242, 242, 242));
        MsgTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        MsgTxt.setBorder(null);
        MsgTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsgTxtActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 102, 0));
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(107, 112, 92)));

        jLabel4.setBackground(new java.awt.Color(107, 112, 92));
        jLabel4.setText("Message Subject");

        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(107, 112, 92)));

        jLabel6.setBackground(new java.awt.Color(107, 112, 92));
        jLabel6.setText("Message Text");

        MsgSub.setBackground(new java.awt.Color(242, 242, 242));
        MsgSub.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        MsgSub.setBorder(null);

        mail.setBackground(new java.awt.Color(242, 242, 242));
        mail.setToolTipText("A reply will be sent to this E-mail");
        mail.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MsgTxt)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MsgSub)
                    .addComponent(mail, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(MsgSub, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MsgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jButton1.setBackground(new java.awt.Color(107, 112, 92));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SEND");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         ImageIcon errIcon = new ImageIcon("C:\\\\Users\\\\windows-10\\\\OneDrive\\\\Files-OD\\\\NetBeansProjects\\\\BetaExpenseManager\\\\src\\\\Img\\\\err100.png");
        ImageIcon okIcon = new ImageIcon("C:\\\\Users\\\\windows-10\\\\OneDrive\\\\Files-OD\\\\NetBeansProjects\\\\BetaExpenseManager\\\\src\\\\Img\\\\check100.png");
        try {
            // TODO add your handling code here:

            String sub = MsgSub.getText();
            String email = mail.getText();
            String msg = MsgTxt.getText();
            if(email.isEmpty() || msg.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please fill up all the required fields: e-mail and message", "Error", JOptionPane.ERROR_MESSAGE, errIcon);
            }else if(!msg.isEmpty() && (email.contains("@gmail.com") || email.contains("@yahoo.com"))){
                pst = con.prepareStatement("INSERT INTO contacttable (msgSub,mail,msgTxt) VALUES(?, ?, ?)");
                pst.setString(1, sub);
                pst.setString(2, email);
                pst.setString(3, msg);
            }else if(!email.contains("@gmail.com") || !email.contains("@yahoo.com")){
                JOptionPane.showMessageDialog(null, "Please enter a valid e-mail", "Invalid Entry", JOptionPane.ERROR_MESSAGE, errIcon);
            }
            int k = pst.executeUpdate(); 
            
            if(k==1){
                JOptionPane.showMessageDialog(null, "Message Successfully Sent!", "Sent", JOptionPane.PLAIN_MESSAGE, okIcon);
                //todo add an ok icon in the message dialog
                //TODO set text of labels here 
            }else{
                JOptionPane.showMessageDialog(null, "Message Failed to Send", "Error", JOptionPane.ERROR_MESSAGE, errIcon);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddBudgetPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void MsgTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsgTxtActionPerformed
        // TODO add your handling code here://no
    }//GEN-LAST:event_MsgTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MsgSub;
    private javax.swing.JTextField MsgTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mail;
    // End of variables declaration//GEN-END:variables
}
