/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.sql.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author windows-10
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Color DefaultColor, ClickedColor;
    public Home() {
        
        initComponents();
        
        //colors for the buttons when clicked 
        ClickedColor = new Color(107,112,92); //dark green
        DefaultColor = new Color(183, 183, 164); //light green
       
        //Set default color to pan when clicked
        BudgetMenu.setBackground(DefaultColor);
        ExpenseMenu.setBackground(DefaultColor);
        SettingsMenu.setBackground(DefaultColor);
        ContactMenu.setBackground(DefaultColor);
        
        //set empty Expense as a default panel to show when the app starts 
        EmptyExpense ee = new EmptyExpense(); 
        ee.setSize(900, 450);
        MenuBoard.add(ee).setVisible(true);
        MenuBoard.setVisible(true);
            MenuBoard.revalidate();
            MenuBoard.repaint();
    }
    //for other panels access
    public JPanel getMenuBoard() {
        return MenuBoard;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BudgetMenu = new javax.swing.JPanel();
        BudgetLbl = new javax.swing.JLabel();
        ExpenseMenu = new javax.swing.JPanel();
        ExpenseLbl = new javax.swing.JLabel();
        SettingsMenu = new javax.swing.JPanel();
        SettingsLbl = new javax.swing.JLabel();
        ContactMenu = new javax.swing.JPanel();
        ContactLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MenuLbl = new javax.swing.JLabel();
        ClosePanel = new javax.swing.JPanel();
        CloseBtn = new javax.swing.JLabel();
        MenuBoard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(183, 183, 164));

        BudgetMenu.setBackground(new java.awt.Color(183, 183, 164));
        BudgetMenu.setAutoscrolls(true);
        BudgetMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BudgetMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BudgetMenuMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BudgetMenuMousePressed(evt);
            }
        });

        BudgetLbl.setBackground(new java.awt.Color(183, 183, 164));
        BudgetLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BudgetLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BudgetLblLight.png"))); // NOI18N
        BudgetLbl.setToolTipText("");
        BudgetLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BudgetLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BudgetLblMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BudgetLblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BudgetMenuLayout = new javax.swing.GroupLayout(BudgetMenu);
        BudgetMenu.setLayout(BudgetMenuLayout);
        BudgetMenuLayout.setHorizontalGroup(
            BudgetMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BudgetMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(BudgetLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BudgetMenuLayout.setVerticalGroup(
            BudgetMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BudgetMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BudgetLbl)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ExpenseMenu.setBackground(new java.awt.Color(183, 183, 164));
        ExpenseMenu.setAutoscrolls(true);
        ExpenseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpenseMenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExpenseMenuMousePressed(evt);
            }
        });

        ExpenseLbl.setBackground(new java.awt.Color(183, 183, 164));
        ExpenseLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExpenseLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/expenseDark.png"))); // NOI18N
        ExpenseLbl.setToolTipText("");
        ExpenseLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpenseLblMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExpenseLblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ExpenseMenuLayout = new javax.swing.GroupLayout(ExpenseMenu);
        ExpenseMenu.setLayout(ExpenseMenuLayout);
        ExpenseMenuLayout.setHorizontalGroup(
            ExpenseMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExpenseMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ExpenseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ExpenseMenuLayout.setVerticalGroup(
            ExpenseMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExpenseMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ExpenseLbl)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        SettingsMenu.setBackground(new java.awt.Color(183, 183, 164));
        SettingsMenu.setAutoscrolls(true);
        SettingsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SettingsMenuMousePressed(evt);
            }
        });

        SettingsLbl.setBackground(new java.awt.Color(183, 183, 164));
        SettingsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SettingsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/settingsDark.png"))); // NOI18N
        SettingsLbl.setToolTipText("");
        SettingsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsLblMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SettingsLblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout SettingsMenuLayout = new javax.swing.GroupLayout(SettingsMenu);
        SettingsMenu.setLayout(SettingsMenuLayout);
        SettingsMenuLayout.setHorizontalGroup(
            SettingsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(SettingsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SettingsMenuLayout.setVerticalGroup(
            SettingsMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(SettingsLbl)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ContactMenu.setBackground(new java.awt.Color(183, 183, 164));
        ContactMenu.setAutoscrolls(true);
        ContactMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactMenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ContactMenuMousePressed(evt);
            }
        });

        ContactLbl.setBackground(new java.awt.Color(183, 183, 164));
        ContactLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContactLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/messageDark.png"))); // NOI18N
        ContactLbl.setToolTipText("");
        ContactLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactLblMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ContactLblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ContactMenuLayout = new javax.swing.GroupLayout(ContactMenu);
        ContactMenu.setLayout(ContactMenuLayout);
        ContactMenuLayout.setHorizontalGroup(
            ContactMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ContactLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        ContactMenuLayout.setVerticalGroup(
            ContactMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ContactLbl)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SettingsMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExpenseMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BudgetMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContactMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BudgetMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExpenseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(SettingsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(ContactMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, 450));

        jPanel2.setBackground(new java.awt.Color(107, 112, 92));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/100xlogo.png"))); // NOI18N

        MenuLbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        MenuLbl.setForeground(new java.awt.Color(255, 255, 255));
        MenuLbl.setText("CashControl");

        ClosePanel.setBackground(new java.awt.Color(107, 112, 92));
        ClosePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosePanelMouseClicked(evt);
            }
        });

        CloseBtn.setBackground(new java.awt.Color(107, 112, 92));
        CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-close-24.png"))); // NOI18N
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ClosePanelLayout = new javax.swing.GroupLayout(ClosePanel);
        ClosePanel.setLayout(ClosePanelLayout);
        ClosePanelLayout.setHorizontalGroup(
            ClosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClosePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseBtn)
                .addContainerGap())
        );
        ClosePanelLayout.setVerticalGroup(
            ClosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClosePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 596, Short.MAX_VALUE)
                .addComponent(ClosePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(MenuLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ClosePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        MenuBoard.setBackground(new java.awt.Color(248, 247, 242));

        javax.swing.GroupLayout MenuBoardLayout = new javax.swing.GroupLayout(MenuBoard);
        MenuBoard.setLayout(MenuBoardLayout);
        MenuBoardLayout.setHorizontalGroup(
            MenuBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        MenuBoardLayout.setVerticalGroup(
            MenuBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(MenuBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 900, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BudgetMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BudgetMenuMousePressed
        // TODO add your handling code here:
        BudgetMenu.setBackground(ClickedColor);
        ExpenseMenu.setBackground(DefaultColor);
        SettingsMenu.setBackground(DefaultColor);
        ContactMenu.setBackground(DefaultColor);
       
        MenuLbl.setText("Budget");
        BudgetLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/BudgetLbl.png"));
        ExpenseLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/expenseDark.png"));
        SettingsLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/settingsDark.png"));
        ContactLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/messageDark.png"));
        
    }//GEN-LAST:event_BudgetMenuMousePressed

    private void ExpenseMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpenseMenuMousePressed
        // TODO add your handling code here:
        BudgetMenu.setBackground(DefaultColor);
        ExpenseMenu.setBackground(ClickedColor);
        SettingsMenu.setBackground(DefaultColor);
        ContactMenu.setBackground(DefaultColor);
        
        MenuLbl.setText("Expenses");
        BudgetLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/BudgetLblLight.png"));
        ExpenseLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/expenseLight.png"));
        SettingsLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/settingsDark.png"));
        ContactLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/messageDark.png"));
        
    }//GEN-LAST:event_ExpenseMenuMousePressed

    private void SettingsMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMenuMousePressed
        // TODO add your handling code here:
        BudgetMenu.setBackground(DefaultColor);
        ExpenseMenu.setBackground(DefaultColor);
        SettingsMenu.setBackground(ClickedColor);
        ContactMenu.setBackground(DefaultColor);
        MenuLbl.setText("Settings");
        
        BudgetLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/BudgetLblLight.png"));
        ExpenseLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/expenseDark.png"));
        SettingsLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/settingsLight.png"));
        ContactLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/messageDark.png"));
    }//GEN-LAST:event_SettingsMenuMousePressed

    private void ContactMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactMenuMousePressed
        // TODO add your handling code here:
        BudgetMenu.setBackground(DefaultColor);
        ExpenseMenu.setBackground(DefaultColor);
        SettingsMenu.setBackground(DefaultColor);
        ContactMenu.setBackground(ClickedColor);
        
        MenuLbl.setText("Contact");
        //setNewIcon Light and Dark values
                BudgetLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/BudgetLblLight.png"));
        ExpenseLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/expenseDark.png"));
        SettingsLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/settingsDark.png"));
        ContactLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/messageLight.png"));
       

    }//GEN-LAST:event_ContactMenuMousePressed

    private void BudgetLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BudgetLblMousePressed
        // TODO add your handling code here:
        BudgetMenu.setBackground(ClickedColor);
        ExpenseMenu.setBackground(DefaultColor);
        SettingsMenu.setBackground(DefaultColor);
        ContactMenu.setBackground(DefaultColor);
       
        MenuLbl.setText("Budget");
        BudgetLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/BudgetLbl.png"));
        ExpenseLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/expenseDark.png"));
        SettingsLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/settingsDark.png"));
        ContactLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/messageDark.png"));
    }//GEN-LAST:event_BudgetLblMousePressed

    private void ExpenseLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpenseLblMousePressed
        // TODO add your handling code here:
        BudgetMenu.setBackground(DefaultColor);
        ExpenseMenu.setBackground(ClickedColor);
        SettingsMenu.setBackground(DefaultColor);
        ContactMenu.setBackground(DefaultColor);
        
        MenuLbl.setText("Expenses");
        BudgetLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/BudgetLblLight.png"));
        ExpenseLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/expenseLight.png"));
        SettingsLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/settingsDark.png"));
        ContactLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/messageDark.png"));
    }//GEN-LAST:event_ExpenseLblMousePressed

    private void SettingsLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsLblMousePressed
        // TODO add your handling code here:
         BudgetMenu.setBackground(DefaultColor);
        ExpenseMenu.setBackground(DefaultColor);
        SettingsMenu.setBackground(ClickedColor);
        ContactMenu.setBackground(DefaultColor);
        MenuLbl.setText("Settings");
                BudgetLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/BudgetLblLight.png"));
        ExpenseLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/expenseDark.png"));
        SettingsLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/settingsLight.png"));
        ContactLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/messageDark.png"));
    }//GEN-LAST:event_SettingsLblMousePressed

    private void ContactLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactLblMousePressed
        // TODO add your handling code here:
        BudgetMenu.setBackground(DefaultColor);
        ExpenseMenu.setBackground(DefaultColor);
        SettingsMenu.setBackground(DefaultColor);
        ContactMenu.setBackground(ClickedColor);
        MenuLbl.setText("Contact");
        
        //setNewIcon Light and Dark values
                BudgetLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/BudgetLblLight.png"));
        ExpenseLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/expenseDark.png"));
        SettingsLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/settingsDark.png"));
        ContactLbl.setIcon(new ImageIcon("C:/Users/windows-10/OneDrive/Files-OD/NetBeansProjects/BetaExpenseManager/src/Img/messageLight.png"));
       
    }//GEN-LAST:event_ContactLblMousePressed

    private void BudgetLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BudgetLblMouseClicked
        
        /*BudgetMenuBoard BMB= new BudgetMenuBoard();
        MenuBoard.removeAll();
        MenuBoard.add(BMB).setVisible(true);
        */
        
        BudgetMenuPanel bmp = new BudgetMenuPanel(); 
        bmp.setSize(900, 450);
        MenuBoard.removeAll();
        MenuBoard.add(bmp).setVisible(true);
        MenuBoard.revalidate();
        MenuBoard.repaint();
        System.out.println("Panel visibility: " + bmp.isVisible());
        System.out.println("Panel size: " + bmp.getSize());
        System.out.println("Panel location: " + bmp.getLocation());
         
    }//GEN-LAST:event_BudgetLblMouseClicked

    private void BudgetMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BudgetMenuMouseClicked
        // TODO add your handling code here:
        /*BudgetMenuBoard BMB= new BudgetMenuBoard();
        MenuBoard.removeAll();
        MenuBoard.add(BMB).setVisible(true);
        */
       
        BudgetMenuPanel bmp = new BudgetMenuPanel(); 
        bmp.setSize(900, 450);
        MenuBoard.removeAll();
        MenuBoard.add(bmp).setVisible(true);
        MenuBoard.revalidate();
        MenuBoard.repaint();
        System.out.println("Panel visibility: " + bmp.isVisible());
        System.out.println("Panel size: " + bmp.getSize());
        System.out.println("Panel location: " + bmp.getLocation());
    }//GEN-LAST:event_BudgetMenuMouseClicked

    private void ClosePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePanelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ClosePanelMouseClicked

    private void CloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseBtnMouseClicked

    private void ExpenseLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpenseLblMouseClicked
        // TODO add your handling code here:
        ExpenseMenuPanel emp = new ExpenseMenuPanel(); 
        emp.setSize(900, 450);
        MenuBoard.removeAll();
        MenuBoard.add(emp).setVisible(true);
        MenuBoard.revalidate();
        MenuBoard.repaint();
        System.out.println("Panel visibility: " + emp.isVisible());
        System.out.println("Panel size: " + emp.getSize());
        System.out.println("Panel location: " + emp.getLocation());
    }//GEN-LAST:event_ExpenseLblMouseClicked

    private void ExpenseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpenseMenuMouseClicked
        // TODO add your handling code here:
        ExpenseMenuPanel emp = new ExpenseMenuPanel(); 
        emp.setSize(900, 450);
        MenuBoard.removeAll();
        MenuBoard.add(emp).setVisible(true);
        MenuBoard.revalidate();
        MenuBoard.repaint();
        System.out.println("Panel visibility: " + emp.isVisible());
        System.out.println("Panel size: " + emp.getSize());
        System.out.println("Panel location: " + emp.getLocation());
    }//GEN-LAST:event_ExpenseMenuMouseClicked

    private void SettingsLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsLblMouseClicked
        // TODO add your handling code here:
        SettingsMenuPanel smp = new SettingsMenuPanel(); 
        smp.setSize(900, 450);
        MenuBoard.removeAll();
        MenuBoard.add(smp).setVisible(true);
        MenuBoard.revalidate();
        MenuBoard.repaint();
        System.out.println("Panel visibility: " + smp.isVisible());
        System.out.println("Panel size: " + smp.getSize());
        System.out.println("Panel location: " + smp.getLocation());
    }//GEN-LAST:event_SettingsLblMouseClicked

    private void SettingsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMenuMouseClicked
        // TODO add your handling code here:
        SettingsMenuPanel smp = new SettingsMenuPanel(); 
        smp.setSize(900, 450);
        MenuBoard.removeAll();
        MenuBoard.add(smp).setVisible(true);
        MenuBoard.revalidate();
        MenuBoard.repaint();
        System.out.println("Panel visibility: " + smp.isVisible());
        System.out.println("Panel size: " + smp.getSize());
        System.out.println("Panel location: " + smp.getLocation());
    }//GEN-LAST:event_SettingsMenuMouseClicked

    private void ContactLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactLblMouseClicked
        // TODO add your handling code here:
        ContactMenuPanel cmp = new ContactMenuPanel(); 
        cmp.setSize(900, 450);
        MenuBoard.removeAll();
        MenuBoard.add(cmp).setVisible(true);
        MenuBoard.revalidate();
        MenuBoard.repaint();
        System.out.println("Panel visibility: " + cmp.isVisible());
        System.out.println("Panel size: " + cmp.getSize());
        System.out.println("Panel location: " + cmp.getLocation());
    }//GEN-LAST:event_ContactLblMouseClicked

    private void ContactMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactMenuMouseClicked
        // TODO add your handling code here:
         ContactMenuPanel cmp = new ContactMenuPanel(); 
        cmp.setSize(900, 450);
        MenuBoard.removeAll();
        MenuBoard.add(cmp).setVisible(true);
        MenuBoard.revalidate();
        MenuBoard.repaint();
        System.out.println("Panel visibility: " + cmp.isVisible());
        System.out.println("Panel size: " + cmp.getSize());
        System.out.println("Panel location: " + cmp.getLocation());
    }//GEN-LAST:event_ContactMenuMouseClicked

    private void BudgetMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BudgetMenuMouseEntered
        //no
    }//GEN-LAST:event_BudgetMenuMouseEntered

    private void BudgetLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BudgetLblMouseEntered
        // no
    }//GEN-LAST:event_BudgetLblMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BudgetLbl;
    private javax.swing.JPanel BudgetMenu;
    private javax.swing.JLabel CloseBtn;
    private javax.swing.JPanel ClosePanel;
    private javax.swing.JLabel ContactLbl;
    private javax.swing.JPanel ContactMenu;
    private javax.swing.JLabel ExpenseLbl;
    private javax.swing.JPanel ExpenseMenu;
    private javax.swing.JPanel MenuBoard;
    private javax.swing.JLabel MenuLbl;
    private javax.swing.JLabel SettingsLbl;
    private javax.swing.JPanel SettingsMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
