/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

//imports for needed packages
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author windows-10
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Connect();
    }
    //pictures for message dialogs
    ImageIcon errIcon = new ImageIcon("C:\\Users\\windows-10\\OneDrive\\Files-OD\\NetBeansProjects\\BetaExpenseManager\\src\\Img\\err100.png");
    ImageIcon okIcon = new ImageIcon("C:\\Users\\windows-10\\OneDrive\\Files-OD\\NetBeansProjects\\BetaExpenseManager\\src\\Img\\check100.png");
    
    //declaration as
    Connection con; 
    ResultSet rs; 
    PreparedStatement pst;
    
//function to connect to database
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cashcontrol_db", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Failed");
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Failed");
        }
        
    }
    //check if there's a record of account within the database
    //
    public boolean verifyUserExists(String username, int pin) {
        
        try {
            // Establish a database connection
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/cashcontrol_db", "root", "");

            // Prepare the SQL query
            String query = "SELECT COUNT(*) FROM signup WHERE New_Username = ? AND NewPin = ?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, username);
            statement.setInt(2, pin);

            // Execute the query
            ResultSet resultSet = statement.executeQuery();
            resultSet.next();

            // Get the count of rows returned
            int count = resultSet.getInt(1);

            // Close the database resources
            resultSet.close();
            statement.close();
            connection.close();

            // Return true if a user with the provided username and PIN exists, false otherwise
            return count > 0;
        } catch (SQLException e) {
   
            e.printStackTrace();
            
            
        
            return false;
        }
    }
    //change Jframes
    private void switchToHome() {
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }
     private void switchToSign(){
         SignUp sign = new SignUp(); 
         sign.setVisible(true); 
         this.setVisible(false);
     }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        unPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LogBtn = new javax.swing.JToggleButton();
        pinTF = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        signIn = new javax.swing.JPanel();
        signInlbl = new javax.swing.JLabel();
        forgot = new javax.swing.JPanel();
        forgotlbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        UnTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(107, 112, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unPanel.setBackground(new java.awt.Color(183, 183, 164));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        LogBtn.setBackground(new java.awt.Color(107, 112, 92));
        LogBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LogBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogBtn.setText("LOGIN");
        LogBtn.setBorder(null);
        LogBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogBtnMouseClicked(evt);
            }
        });
        LogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtnActionPerformed(evt);
            }
        });

        pinTF.setBackground(new java.awt.Color(183, 183, 164));
        pinTF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinTF.setForeground(new java.awt.Color(255, 255, 255));
        pinTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinTF.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PIN");

        signIn.setBackground(new java.awt.Color(183, 183, 164));
        signIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInMouseClicked(evt);
            }
        });

        signInlbl.setBackground(new java.awt.Color(183, 183, 164));
        signInlbl.setForeground(new java.awt.Color(107, 112, 92));
        signInlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInlbl.setText("Sign Up? Click here");
        signInlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInlblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout signInLayout = new javax.swing.GroupLayout(signIn);
        signIn.setLayout(signInLayout);
        signInLayout.setHorizontalGroup(
            signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signInlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
        signInLayout.setVerticalGroup(
            signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInLayout.createSequentialGroup()
                .addComponent(signInlbl)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        forgot.setBackground(new java.awt.Color(183, 183, 164));

        forgotlbl.setBackground(new java.awt.Color(183, 183, 164));
        forgotlbl.setForeground(new java.awt.Color(107, 112, 92));
        forgotlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotlbl.setText("Forgot Password? Click here");
        forgotlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotlblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout forgotLayout = new javax.swing.GroupLayout(forgot);
        forgot.setLayout(forgotLayout);
        forgotLayout.setHorizontalGroup(
            forgotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forgotlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        forgotLayout.setVerticalGroup(
            forgotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forgotlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("USERNAME");

        UnTF.setBackground(new java.awt.Color(183, 183, 164));
        UnTF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UnTF.setForeground(new java.awt.Color(255, 255, 255));
        UnTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UnTF.setBorder(null);

        javax.swing.GroupLayout unPanelLayout = new javax.swing.GroupLayout(unPanel);
        unPanel.setLayout(unPanelLayout);
        unPanelLayout.setHorizontalGroup(
            unPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(unPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(unPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pinTF, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addComponent(LogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(forgot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(unPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(UnTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        unPanelLayout.setVerticalGroup(
            unPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinTF, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(LogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel1.add(unPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 530, 550));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/350LogoEM.png"))); // NOI18N
        jLabel3.setText("CashDaddy");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 350, 210));

        welcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("WELCOME BACK!");
        jPanel1.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 349, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CashControl");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 349, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtnActionPerformed
        // TODO add your handling code here:
        String New_Username = UnTF.getText();
        String pinStr = pinTF.getText(); 
        int NewPin = Integer.parseInt(pinStr);
        
        
        boolean userExists = verifyUserExists(New_Username, NewPin);
        
        if (userExists) {
            // User exists in the database and PIN is correct, proceed with the login process
            // Implement your login logic here
            JOptionPane.showMessageDialog(null, "You've successfully logged in!", "Welcome" + New_Username, JOptionPane.PLAIN_MESSAGE, okIcon);
            switchToHome();
        } else {
            // User does not exist or PIN is incorrect, show an appropriate message or take necessary action
            JOptionPane.showMessageDialog(null, "Invalid username or PIN. Please try again.", "Login", JOptionPane.ERROR_MESSAGE, errIcon);
        }
    }//GEN-LAST:event_LogBtnActionPerformed

    private void LogBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogBtnMouseClicked
         
        //none
        
    }//GEN-LAST:event_LogBtnMouseClicked

    private void forgotlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlblMouseClicked
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Please input your One Time Code we sent to your e-mail to Login.", "Security Code Sent", JOptionPane.PLAIN_MESSAGE );
    }//GEN-LAST:event_forgotlblMouseClicked

    private void signInlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInlblMouseClicked
        // TODO add your handling code here:
        switchToSign();
    }//GEN-LAST:event_signInlblMouseClicked

    private void signInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInMouseClicked
        // TODO add your handling code here:
        switchToSign();
    }//GEN-LAST:event_signInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton LogBtn;
    private javax.swing.JTextField UnTF;
    private javax.swing.JPanel forgot;
    private javax.swing.JLabel forgotlbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pinTF;
    private javax.swing.JPanel signIn;
    private javax.swing.JLabel signInlbl;
    private javax.swing.JPanel unPanel;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
