/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms;

import java.awt.Container;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author windows-10
 */
public class SettingsMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingsMenuPanel
     */
    public SettingsMenuPanel() {
        initComponents();
    }
     ImageIcon errIcon = new ImageIcon("C:\\\\Users\\\\windows-10\\\\OneDrive\\\\Files-OD\\\\NetBeansProjects\\\\BetaExpenseManager\\\\src\\\\Img\\\\err100.png");
     ImageIcon okIcon = new ImageIcon("C:\\\\Users\\\\windows-10\\\\OneDrive\\\\Files-OD\\\\NetBeansProjects\\\\BetaExpenseManager\\\\src\\\\Img\\\\check100.png");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SettingsFtrBtn = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        secu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        laldl1 = new javax.swing.JLabel();
        laldl2 = new javax.swing.JLabel();
        AboutUs = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SettingsFtrBtn.setBackground(new java.awt.Color(204, 204, 204));

        jPanel5.setBackground(new java.awt.Color(248, 247, 242));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(107, 112, 92));
        jLabel10.setText("General");

        jLabel6.setBackground(new java.awt.Color(248, 247, 242));
        jLabel6.setText("Currency Format");

        jLabel7.setText("Show Decimal Digit");

        jLabel8.setText("Dark Mode");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(248, 247, 242));

        label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label.setForeground(new java.awt.Color(107, 112, 92));
        label.setText("Security");

        secu.setText("Activate Security");
        secu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secu, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(secu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(248, 247, 242));

        label1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(107, 112, 92));
        label1.setText("Info");

        laldl1.setText("Privacy Policy                             ");
        laldl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laldl1MouseClicked(evt);
            }
        });

        laldl2.setText("Delete All Data");
        laldl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laldl2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laldl1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1)
                    .addComponent(laldl2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laldl1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laldl2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SettingsFtrBtnLayout = new javax.swing.GroupLayout(SettingsFtrBtn);
        SettingsFtrBtn.setLayout(SettingsFtrBtnLayout);
        SettingsFtrBtnLayout.setHorizontalGroup(
            SettingsFtrBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SettingsFtrBtnLayout.setVerticalGroup(
            SettingsFtrBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsFtrBtnLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(SettingsFtrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        AboutUs.setBackground(new java.awt.Color(49, 69, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("CashControl");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("About");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Version 1.9.0");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(49, 69, 40));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("    Easy-to-use expense manager to \n keep track of your income and expenses;  \n monitory your spending habits, and; \n create budgets to help you stay on track.  \n Set financials goals and track your \n progress towards achieving them.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(49, 69, 40));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("    Our team is dedicated to continuously   \n improving and enhancing Cash Control to \n meet the ever-changing needs of our users. \n We strive to provide the best user \n experience possible and are always \n open to feedback and suggestions.");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setBorder(null);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 242, 242));
        jLabel11.setText("CC.org");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Team");

        javax.swing.GroupLayout AboutUsLayout = new javax.swing.GroupLayout(AboutUs);
        AboutUs.setLayout(AboutUsLayout);
        AboutUsLayout.setHorizontalGroup(
            AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(AboutUsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AboutUsLayout.setVerticalGroup(
            AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 300, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void laldl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laldl1MouseClicked
        // TODO add your handling code here:add dialog pop up box 
            
            JOptionPane.showMessageDialog(null, """
                                                  <html><b><font size="+2">Privacy Policy </font></b></html>
                                                  \u2022 Improve, personalize, and expand our website
                                                  \u2022 Communicate with you, either directly or through one of our partners, including for customer service, 
                                                      to provide you with updates and other information relating to the website, and for marketing and promotional purposes
                                                  \u2022 Send you emails
                                                  \u2022 Find and prevent fraud
                                                   
                                                  <html><b><font size="+1">Log Files</font></b></html>\n 
                                                   CashControl follows a standard procedure of using log files. 
                                                   These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. 
                                                   The information collected by log files include internet protocol (IP) addresses, browser type, 
                                                       Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. 
                                                   These are not linked to any information that is personally identifiable. 
                                                   The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.
                                                   
                                                  <html><b><font size="+1">GDPR Data Protection Rights </font></b></html><br><br>We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:
                                                  \u2022 The right to access \u2013 You have the right to request copies of your personal data. We may charge you a small fee for this service. 
                                                  \u2022 The right to rectification \u2013 You have the right to request that we correct any information you believe is inaccurate. 
                                                     You also have the right to request that we complete the information you believe is incomplete.
                                                  \u2022 The right to erasure \u2013 You have the right to request that we erase your personal data, under certain conditions.
                                                  \u2022 The right to restrict processing \u2013 You have the right to request that we restrict the processing of your personal data, under certain conditions.
                                                  \u2022 The right to object to processing \u2013 You have the right to object to our processing of your personal data, under certain conditions.
                                                  \u2022 The right to data portability \u2013 You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.""", "Privacy Policy", JOptionPane.PLAIN_MESSAGE);

        
    }//GEN-LAST:event_laldl1MouseClicked

    private void secuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secuMouseClicked
        // TODO add your handling code here:
        
        Object[] options = {"Yes", "No"};

        int choice = JOptionPane.showOptionDialog(
            null,
            "Activate Security",
            "Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[1]  // Default selection (optional)
        );

        if (choice == JOptionPane.YES_OPTION) {
            // User clicked "Yes"
            System.out.println("User selected: Yes");
            
            // Perform actions for "Yes" option
            JOptionPane.showMessageDialog(null, "Security is now Activated", "Security On", JOptionPane.PLAIN_MESSAGE,  okIcon);
        } else if (choice == JOptionPane.NO_OPTION) {
            // User clicked "No"
            System.out.println("User selected: No");
            // Perform actions for "No" option
            JOptionPane.showMessageDialog(null, "Security is deactivted", "Security Off", JOptionPane.PLAIN_MESSAGE,  okIcon);
        } 

    }//GEN-LAST:event_secuMouseClicked

    private void laldl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laldl2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Are you sure you want to delete all your data", "Confirmation", JOptionPane.PLAIN_MESSAGE,  errIcon);
        Object[] options = {"Delete All", "Cancel"};

        int choice = JOptionPane.showOptionDialog(
                    null,
                    "Activate Security",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[1]  // Default selection (optional)
                );

                if (choice == JOptionPane.YES_OPTION) {
                    // User clicked "Yes"
                    System.out.println("User selected: Yes");
                    
                    // Perform actions for "Yes" option
                    JOptionPane.showMessageDialog(null, "All your data has been delete", "Security On", JOptionPane.PLAIN_MESSAGE,  okIcon);
                } else if (choice == JOptionPane.NO_OPTION) {
                    // User clicked "No"
                    System.out.println("User selected: No");
                    // Perform actions for "No" option
                    //None because it will just go back
                } 

    }//GEN-LAST:event_laldl2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutUs;
    private javax.swing.JPanel SettingsFtrBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel laldl1;
    private javax.swing.JLabel laldl2;
    private javax.swing.JLabel secu;
    // End of variables declaration//GEN-END:variables
}
